[package]
name = "textedit"
version = "0.1.0"
author = ["Aarav"]
edition = "2021"

[dependencies]
tauri = { version = "2.0", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-opener = "2"

[build-dependencies]
tauri-build = { version = "2.0", features = [] }
