[package]
name = "textedit"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "2.0", features = ["api-all"] }

[build-dependencies]
tauri-build = { version = "2.0", features = [] }
